"""Artifact exporters for interoperability with external eval runners."""
from __future__ import annotations

import json
import re
from pathlib import Path

from .types import BenchmarkDataset, TaskType


def _safe_task_name(value: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", value.lower()).strip("_")
    return name or "evalclaw_task"


def _yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_lm_eval_artifacts(dataset: BenchmarkDataset, out_dir: Path) -> dict[str, Path]:
    """Write a minimal lm-eval-harness compatible dataset and task YAML.

    The YAML uses local jsonl files. It is intentionally conservative and most
    useful for MCQ/short-answer style tasks; open-generation items still export
    with their rubrics in metadata so they can be adapted manually or by a later
    runner.
    """
    artifacts_dir = out_dir / "lm-eval"
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    task_name = _safe_task_name(dataset.spec.id)
    jsonl_path = artifacts_dir / f"{task_name}.jsonl"
    yaml_path = artifacts_dir / f"{task_name}.yaml"
    metadata_path = artifacts_dir / f"{task_name}.metadata.json"

    with jsonl_path.open("w", encoding="utf-8") as handle:
        for item in dataset.items:
            record = {
                "id": item.id,
                "dimension_id": item.dimension_id,
                "question": item.prompt,
                "choices": item.choices,
                "answer": item.answer or "",
                "rubric": item.rubric or "",
                "difficulty": item.difficulty.value,
                "task_type": item.task_type.value,
                "source": item.source.model_dump(mode="json"),
                "tags": item.tags,
            }
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")

    output_type = "multiple_choice" if any(
        item.task_type == TaskType.multiple_choice for item in dataset.items
    ) else "generate_until"
    requires_custom_judge = any(
        item.task_type in {TaskType.open_generation, TaskType.multi_turn}
        for item in dataset.items
    )
    metric = "acc" if output_type == "multiple_choice" else "exact_match"
    yaml_lines = [
        f"task: {task_name}",
        "dataset_path: json",
        "dataset_kwargs:",
        "  data_files:",
        f"    test: {_yaml_scalar(str(jsonl_path))}",
        "test_split: test",
        f"output_type: {output_type}",
        "doc_to_text: \"{{question}}\"",
        "doc_to_target: \"{{answer}}\"",
    ]
    if output_type == "multiple_choice":
        yaml_lines.append("doc_to_choice: \"{{choices}}\"")
    yaml_lines.extend(
        [
            "metric_list:",
            f"  - metric: {metric}",
            "    aggregation: mean",
            "    higher_is_better: true",
            "metadata:",
            f"  source: {_yaml_scalar('evalclaw')}",
            f"  objective: {_yaml_scalar(dataset.spec.objective)}",
            f"  evalclaw_requires_custom_judge: {str(requires_custom_judge).lower()}",
            "",
        ]
    )
    yaml_text = "\n".join(yaml_lines)
    yaml_path.write_text(yaml_text, encoding="utf-8")
    metadata_path.write_text(
        json.dumps(
            {
                "spec": dataset.spec.model_dump(mode="json"),
                "item_count": len(dataset.items),
                "notes": (
                    "Generated by EvaluationClaw. Open-generation rubrics are exported "
                    "as metadata; exact lm-eval judging may require a custom metric."
                ),
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return {"jsonl": jsonl_path, "yaml": yaml_path, "metadata": metadata_path}


def write_artifact_manifest(
    out_dir: Path,
    *,
    package_path: Path,
    report_path: Path,
    lm_eval_paths: dict[str, Path],
) -> Path:
    """Write a stable machine-readable index of generated artifacts."""
    manifest_path = out_dir / "manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "package": str(package_path),
                "report": str(report_path),
                "lm_eval": {key: str(value) for key, value in lm_eval_paths.items()},
                "notes": [
                    "package is the canonical EvaluationClaw JSON payload.",
                    "report is a human-readable Markdown summary.",
                    "lm_eval artifacts are interoperability exports and may require custom judging for open-generation tasks.",
                ],
            },
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return manifest_path
